
site:
  about:
    siteName: Strikt
    siteDescription: Strikt is an assertion library for Kotlin intended for use with a test runner such as JUnit or Spek.

theme:
  social:
    other:
      - label: 'GitHub'
        icon: 'fa-github'
        link: 'https://github.com/robfletcher/strikt/'
        buttonColor: 'dark'
      - label: 'Slack'
        icon: 'fa-slack-hash'
        link: 'https://kotlinlang.slack.com/messages/CAR7KJ96J'
        buttonColor: 'danger'
      - label: 'Twitter'
        icon: 'fa-twitter'
        link: 'https://twitter.com/stri_kt'
        buttonColor: 'info'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
      icon: 'home'
    - type: 'page'
      title: 'About'
      itemId: 'About Strikt'
      icon: 'info-circle'
    - type: 'submenu'
      title: 'User Guide'
      icon: 'book'
      menu:
        - type: 'wiki'
          section: 'user-guide'
    - type: 'submenu'
      title: 'API'
      icon: 'book'
      menu:
        - type: 'page'
          title: 'Strikt Core'
          itemId: 'strikt.api'
        - type: 'page'
          title: 'Strikt Assertions'
          itemId: 'strikt.assertions'
        - type: 'page'
          title: 'Strikt Protobuf'
          itemId: 'strikt.protobuf'

allPages:
  components:
    - type: 'pageContent'

wiki:
  sections:
    - 'user-guide'

#services:
#  generators:
#    disabled:
#      - 'kotlindoc'

kotlindoc:
  sourceDirs:
    - '../../../../strikt-core/src/main/kotlin/'
    - '../../../../strikt-protobuf/src/main/kotlin/'
